### PR TITLE
deleting draft files for site and page during layout editing

### PR DESCRIPTION
**Pull request by ManushiM**

### CODE REVIEW

**Comment by ajturner** [comment]
I think this looks OK. @robertvo824 can you look at this as it relates to Python + Sites domain.

**Review by robertvo824 — COMMENTED** [review]
Just one comment:

Since `Site.update_layout()` and and `Page.update_layout()` contain the same logic, can you just inherit from a common parent class or just call `Site.update_layout()` within the Page class and pass in self? Unless I'm missing something here... just thinking of eliminating duplicate code since the file is rather large already.

**Comment by ManushiM** [comment]
Thanks for the useful suggestion @robertvo824 ! I changed the `Page.update_layout()` method to call the method from `Site`.

**Review by robertvo824 — APPROVED** [review]
Looks good! Thanks

**Pull request merged**
